### ISSUE TITLE
InvalidCastException within RestSharp

### ISSUE THREAD

**Issue by talbotmcinnis** [jonas0007/Jira.SDK#2]
Great project, , it was so encouraging at first.

I am calling Sprint.GetIssues and the IRestReponse object indicates an exception is occuring:
{"Unable to cast object of type 'System.String' to type 'System.Collections.Generic.IDictionary`2[System.String,System.Object]'."}.

I can see the raw response and it contains a ton of data.  Where can I even begin debugging this?

**Comment by talbotmcinnis** [comment]
I got to the bottom of this.  I believe this code has code which is specific to your instance of jira.  Specifically the custom field IDs are different for me.  I remapped them, removed some, added some and now it works like a charm.  Although theoretically possible to automate this (I think), I can understand why its hard coded, but this should be documented much better, perhaps with a template of an extension class to add one's own custom fields.

**Comment by jonas0007** [comment]
Hi, I mensioned this briefly on the home page of the project but I will put this issue more in the picture.
Currently I am having issues with deserializing custom fields using the build in RestSharp JSON deserializer. The way the custom fields are embedded in the JSON result makes it hard to automate this.

I have a few ideas on how to solve this problem but haven't yet had the time to implement it.

One way would be to use a different method in the JiraClient class just for fetching Issues from Jira. In addition to casting the result into a Issue object I would then add a list of all the custom field by parsing the JSON file in code.

The other way would be to remove the knowledge of "custom fields" from the SDK and make all methods and classes involving Issues generic. This generic type would then have to be inherited from Jira and developers using the SDK would create there own Issue class including the custom fields.

**Comment by talbotmcinnis** [comment]
Typing on a phone, excuse the brevity.

Id vote for making issue an interface, and creating a base class with standard fields.  
Developers wanting custom field support would extend the base class and use a templated?? Version of the client class.  Not sure that last step is possible though.

Even requiring code changes isn't that bad, just the day i lost realizing that i had to :)

Thanks again for the great project.

Talbot McInnis
Operations Director
787 Networks Inc
Home of Bowling Music Network & controlPLAY.
Phone: 1-866-684-8324 ext. 228
Fax: 1-866-295-4281
talbot.mcinnis@787networks.com

**Comment by jonas0007** [comment]
I'm trying to wrap my head around the issue yet I can't see a decent solution involving an interface or base class. The problem is the custom fields come a properties on the Fields property of an issue in the JSON structure.

So developers using the SDK should have the ability to indicate which type to use as the class implementing the IssueFields property.

One solution I see is to make the Issue class generic. The generic type would be the type used for the Fields property. But if I want to do that, that means I will need to provide the IssueFields type to every corner of the SDK using an Issue.

Any ideas other then hooking into the deserialisation code and manually deserialising the Issues?

**Comment by talbotmcinnis** [comment]
Could custom field be deserialized as strings by default, and then to access them as specialized fields, the developer could extend the issue class with custom accessor methods, with or without serialization requirements depending on the type?

Talbot McInnis
Operations Director
787 Networks Inc
Home of Bowling Music Network & controlPLAY.
Phone: 1-866-684-8324 ext. 228
Fax: 1-866-295-4281
talbot.mcinnis@787networks.com

**Comment by jonas0007** [comment]
I have managed to change the deserialization code for issues. While deserializing an issue, all custom fields are added to a dictionary. These are then accessible via the Get/SetCustomFieldValue() methods.

Can you verify if this solves your problem?

Note, I have also published a new nuget package including some additional features and bugfixes.

**Comment by talbotmcinnis** [comment]
Ill give it a shot.  Thanks!

Talbot McInnis
Operations Director
787 Networks Inc
Home of Bowling Music Network & controlPLAY.
Phone: 1-866-684-8324 ext. 228
Fax: 1-866-295-4281
talbot.mcinnis@787networks.com

**Comment by jonas0007** [comment]
I'm considering this issue closed. Please raise a new one if you have any more issues with custom fields.
