### ISSUE TITLE
The field 'FixVersions' is empty in an issue

### ISSUE THREAD

**Issue by RubenOuwerkerk** [jonas0007/Jira.SDK#27]
I fixed a bug in the code, Issue.cs line 575-582 where the FixVersion property is set on an issue.

The problem is the use of a capital bij Jira and not by the code :)
After fixing that, the use of JObject is wrong, it should be JArray.

I created a branch with the fix, but somehow I cannot push it to origin (permission denied).

New code:
            FixVersions = new List<ProjectVersion>();
            if (fields.ContainsKey("fixVersions") && fields["fixVersions"] != null)
            {
                JArray versionArray = (JArray)fields["fixVersions"];
                if (versionArray.Count > 0)
                {
                    FixVersions = ((JArray)fields["fixVersions"]).ToObject<List<ProjectVersion>>();
                }
            }

**Comment by jonas0007** [comment]
Hi Ruben,

Thank you for wanting to contribute to this library!

Please create a pull request to merge you branch into master. This way I can review the change (make sure it is compliant with the rest of the code base) and create a new version of the nuget package.

**Comment by RubenOuwerkerk** [comment]
As said, I can't push the branch to origin. It makes no sense to create a pull request if I can't choose my branch...

remote: Permission to jonas0007/Jira.SDK.git denied to RubenOuwerkerk.
fatal: unable to access 'https://github.com/jonas0007/Jira.SDK.git/': The requested URL returned error: 403

**Comment by jonas0007** [comment]
Hi Ruben,

Sorry for the late response. Because of the way this repository is set-up, you need to fork this repository and then create a pull request when you are done. Then you changes will be merged into the master branch of this repository which triggers the automatic creation of a new version of the nuget package.

I'll add this information to the readme.

Kind regards

**Comment by RubenOuwerkerk** [comment]
Thanks for your reply.

Pull request created.

**Comment by tsbwn** [comment]
Hey guys.
I'm expecting this issue now (fixversions comes empty on Jira 6.3.14), but it seems you've fixed it. In NuGet package it says "Tuesday, March 15, 2016" the latest version uploaded. Seems like the version wasn't created automatically.
Can you please upload the latest one to NuGet? Or may be there is a way to make it work for me?
Sorry, I'm noob in  programming & git. 
Thank you for your contribution!

**Comment by jonas0007** [comment]
Hi,

Thank you for pointing this out. Apparently the deployment on AppVeyor is broken and it doesn't create any nuget packages anymore. I'll try to sort this out this evening.


Kind regards

**Comment by jonas0007** [comment]
Hi,

Just got it figgered out. Apperantly AppVeyor changed its build proces causing the nuget pack command to fail. Fixed it and a new version of the nuget package is on its way.
