### ISSUE TITLE
Support source stepping using GitLink

### ISSUE THREAD

**Issue by GeertvanHorrik** [jonas0007/Jira.SDK#3]
Today I was having a few issues with the library (when actually integrating this into GitTools.Core, which is used by GitLink). However, the library is a black box so it's hard to understand where it's going wrong. Would be great if the source would be "steppable".

For more information, see https://github.com/GitTools/GitLink

**Comment by GeertvanHorrik** [comment]
btw. let me know if you need help with this.

**Comment by jonas0007** [comment]
Hi Geert, pleased to here the SDK is actually beeing used. Not sure what I can do to help you, I haven't signed the the library so please feel free to give me some ideas on how I would make my code "steppable".

I'm not having this issue on my local project where visual studio steps into the SDK seamlessly but maybe visual studio is smart enough to recognize the library is a DLL compiled from another visual studio solution on my hard drive.

**Comment by GeertvanHorrik** [comment]
If you build the software locally, it will work, but if you reference a NuGet package, it becomes a black box (because there is no source available). The only thing you have to do is between the build and the creation of the NuGet package you should run GitLink:

```
GitLink.exe c:\source\Jira.SDK -u https://github.com/jonas0007/Jira.SDK -b [branchname]
```

If you have a local .git directory when doing this, this is sufficient:

```
GitLink.exe c:\source\Jira.SDK
```

**Comment by jonas0007** [comment]
I have published a new nuget package including the steps you've added above. Can you please test if this works for you?

**Comment by GeertvanHorrik** [comment]
Don't you have a build script / build server that automatically deploys for you? If not, you might look into AppVeyor (it's free for open source projects if I am not mistaken).

**Comment by jonas0007** [comment]
I'm currently running into bug https://github.com/GitTools/GitLink/issues/42 of the GitLink command line so the new version of the nuget package won't be having gitlink support.

I'll look into a build server for my project. AppVeyor seems to be a paying service even for open source projects.

**Comment by GeertvanHorrik** [comment]
Quote on their front page: "Free for open-source projects."

Make sure you do a full clean before doing a rebuild / running gitlink. What OS / VS language are you using?
